### ISSUE TITLE
Third order upwind left boundary stencil

### ISSUE THREAD

**Issue by kalj** [kalj/StenSeal#12]
Something seems wrong with the third row of the left boundary stencil of the third-order operator:
https://github.com/kalj/StenSeal/blob/master/include/stenseal/operator_lib.h#L44
The `-1` seems a bit odd. I guess the weights should add up to 0. @ylvarydin, can you take a look at that?

**Comment by ylvarydin** [comment]
Den stämmer, raderna skall summera till 0.
